Add vertical and horizontal vane position controls
geoffdavis/esphome-mitsubishiheatpump pull request #109
Opened 2023-08-03 14:14 UTC by nathanjw

- Add vertical and horizontal vane selects as done for Panasonic pumps; https://github.com/DomiStyle/esphome-panasonic-ac
- Add HORIZONTAL and BOTH swing mode options in additon to OFF and VERTICAL
- Fix logging bug causing ESP to crash

Starting from https://github.com/geoffdavis/esphome-mitsubishiheatpump/pull/103 by @seime, extract the vane implementation code and format according to existing style. Leave behind all the reformatting.

2023-08-04 02:33 UTC, SSMCD reviewed
Confirmed working with my MITMSZFH09NA unit.   Thank you!

Recommend disabling the swing mode trait of the climate component if these Horizontal and Vertical selects are used.
See     [Advanced Configuration](https://github.com/geoffdavis/esphome-mitsubishiheatpump/blob/master/README.md#advanced-configuration):
```
supports:
  swing_mode: []
```

2023-08-04 02:33 UTC, SSMCD commented on README.md
> +      name: Horizontal Vane Position
name: ${name} Horizontal Vane

2023-08-04 02:33 UTC, SSMCD commented on README.md
> +      name: Horizontal Vane Position
name: ${name} Vertical Vane

2023-09-04 12:41 UTC, swannet commented
I've tested this PR on my units (MSZ-AP**VGK) and they are working as expected. I've used the by SSMCD on 4th august (line 231 > Horizontal Vane Position > ${name} Vertical Vane)

@geoffdavis sorry to ping you, would you please have a look af this PR to add the functionality to control the vanes?

2023-09-04 16:31 UTC, geoffdavis commented
Can you rebase this onto devel instead of master? I've got some pending commits on the devel branch that I need to package as a release. They're mostly documentation changes.

2023-09-04 16:50 UTC, geoffdavis commented on README.md
This likely went away when I set the base branch to develop. Can you work with @nathanjw on that rebase?

2023-09-05 01:51 UTC, nathanjw commented
Rebased against devel, and caught up to the changes there. I also re-added the models that @seime mentioned.

2023-10-13 20:49 UTC, geoffdavis requested changes
Most units don't support Horizontal or Both swing modes _by default_. Please leave the default set to ['OFF', 'VERTICAL']

2023-10-13 20:50 UTC, geoffdavis commented on README.md
> +    units only support the default. Default: `['OFF', 'VERTICAL', 'HORIZONTAL', 'BOTH']`
The default should be ['OFF', 'VERTICAL']

2023-10-13 20:51 UTC, geoffdavis commented on components/mitsubishi_heatpump/climate.py
> +DEFAULT_SWING_MODES = ["OFF", "VERTICAL", "HORIZONTAL", "BOTH"]
Keep this as ["OFF", "VERTICAL"]

2023-12-17 20:37 UTC, nathanjw commented on components/mitsubishi_heatpump/climate.py
> +DEFAULT_SWING_MODES = ["OFF", "VERTICAL", "HORIZONTAL", "BOTH"]
Done.

2023-12-18 21:54 UTC, SGXander commented
Tested nathanjw:unformat-select and it's working well on MSZ-LN25VG2

2023-12-30 17:11 UTC, geoffdavis commented
> Can this be merged? I Want to get rid of the MELCLOUD integration, but I need this kind of control to be able to do that..

Not until the [change I requested is made](https://github.com/geoffdavis/esphome-mitsubishiheatpump/pull/109#pullrequestreview-1677356783), and the conflicts are resolved.

2023-12-30 23:48 UTC, SGXander commented
I've made a slight alteration at https://github.com/SGXander/esphome-mitsubishiheatpump/tree/split_fix which I'd be happy to PR either here or into nathanjws fork, let me know which. The underlying swicago library specifies "<>" which in nathanjws version is marked as "auto" but during testing I have discovered it is actually "split" (leaving the middle clear and sending air left and right). I've updated this in my fork under the split_fix branch but so far I haven't found the command code to activate auto on the horizontal_vane so have left it out of the options variable.

2023-12-31 00:32 UTC, nathanjw commented
Please take another look. I had adjusted the defaults as requested, but missed that merge conflict. I think that is resolved now.

2024-01-02 19:43 UTC, eclair4151 commented
Whats the best way to test this PR on my Home Assistant install? I tried replacing the external component URL with your branch URL, but it didnt seem to have any effect.

2024-01-02 20:04 UTC, SGXander commented
> Whats the best way to test this PR on my Home Assistant install? I tried replacing the external component URL with your branch URL, but it didnt seem to have any effect.

`external_components:
  - source: github://nathanjw/esphome-mitsubishiheatpump@unformat-select
`

2024-01-05 03:07 UTC, eclair4151 commented
Awesome, thanks! Just tested it out, working for me as well. I wish Home assistant let you customize the HVAC card to allow you to put the swing in the card, oh well :). @SGXander I think you still need to mark the PR ready for review.

2024-01-05 07:50 UTC, SGXander commented
> Awesome, thanks! Just tested it out, working for me as well. I wish Home assistant let you customize the HVAC card to allow you to put the swing in the card, oh well :). @SGXander I think you still need to mark the PR ready for review. 

Not my repo, it's ready to merge already though if you want it to report "split" instead of "auto" then use my fork for now as I don't think nathanjw has updated this one.

2024-01-05 12:01 UTC, eclair4151 commented
Ah whoops, @nathanjw thoughts on adding in support for horizontal vane split position in this PR and marking it ready for review?

2024-01-07 20:31 UTC, SGXander commented
put in https://github.com/nathanjw/esphome-mitsubishiheatpump/pull/1 for the split thing that way it should update this PR if approved

2024-01-30 00:03 UTC, eclair4151 commented
@nathanjw Whats the status on this? If we dont hear back should we just raise a separate PR based on yours SGXander which includes the fix?

2024-01-30 00:53 UTC, nathanjw commented
I think I'd like to get this in as is and then a cosmetic renaming of that horizontal mode could be a much easier followon.

2024-01-30 00:56 UTC, jamiebegin commented
> > Whats the best way to test this PR on my Home Assistant install? I tried replacing the external component URL with your branch URL, but it didnt seem to have any effect.
> 
> ```
> external_components:
>   - source: github://nathanjw/esphome-mitsubishiheatpump@unformat-select
> ```

I'm getting a whole slew of errors when I attempt to compile using this branch. It starts with:
```
In file included from src/esphome.h:33,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.h:20,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.cpp:21:
src/esphome/components/mitsubishi_heatpump/espmhp.h:182:14: error: 'optional' in namespace 'std' does not name a template type
         std::optional<std::chrono::duration<long long, std::ratio<60>>> remote_operating_timeout_;
```

These errors don't happen when using the base branch. I'm not much of a C++ guy so I'm not sure where to start looking for the problem?

2024-01-30 06:35 UTC, swannet commented
@jamiebegin 

You have to add some options to help the compiler use C++17

See the sample below. You've to add the platformio_options with the build_unflag and build_flags

```
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # Set platform options to use c++ 17 instead of 11
  platformio_options:
    build_unflags:
      - "-std=gnu++11"
    build_flags:
      - "-std=gnu++17"

```

2024-02-15 18:31 UTC, davidcd13 commented
Vane selection cannot be integrated into the default home assistant climate card? Is it necessarily a separate card? With Melcloud,  vane position is integrated into the default climate card.

2024-03-16 16:30 UTC, swannet commented
> Vane selection cannot be integrated into the default home assistant climate card? Is it necessarily a separate card? With Melcloud, vane position is integrated into the default climate card.

It is possible, with the "features" you can add to the climate card. And with the service-call-tile-feature add-on from Nerwyn (https://github.com/Nerwyn/service-call-tile-feature):

<img width="493" alt="Screenshot 2024-03-16 at 17 30 11" src="https://github.com/geoffdavis/esphome-mitsubishiheatpump/assets/550021/5d76e545-d068-409c-b5c1-f8c88bb4a705">

```
type: thermostat
entity: climate.airco_
features:
  - style: icons
    hvac_modes:
      - 'off'
      - cool
      - heat
      - fan_only
      - dry
    type: climate-hvac-modes
  - style: dropdown
    fan_modes:
      - auto
      - low
      - medium
      - high
    type: climate-fan-modes
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: select.airco_woonkamer_horizontal_vane_position
        options:
          - option: left
            icon: mdi:chevron-double-left
          - option: left_center
            icon: mdi:chevron-left
          - option: center
            icon: mdi:format-horizontal-align-center
          - option: right_center
            icon: mdi:chevron-right
          - option: right
            icon: mdi:chevron-double-left
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: select.airco_woonkamer_vertical_vane_position
        options:
          - option: up
            icon: mdi:chevron-double-up
          - option: up_center
            icon: mdi:chevron-up
          - option: center
            icon: mdi:format-vertical-align-center
          - option: down_center
            icon: mdi:chevron-down
          - option: down
            icon: mdi:chevron-double-down
show_current_as_primary: false
```

2024-06-23 20:49 UTC, geoffdavis approved these changes

2024-06-23 20:49 UTC, merged